In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x=torch.ones(3,4)
y=torch.zeros(3,4)
z=torch.rand(3,4)

In [3]:
print(f"{x}\n{y}\n{z}")

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.2244, 0.0912, 0.4647, 0.3940],
        [0.8387, 0.4652, 0.1716, 0.9314],
        [0.8973, 0.7838, 0.5076, 0.5120]])


In [4]:
x=torch.empty(3,4)
x

tensor([[2.9048e-35, 0.0000e+00, 3.3631e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.1578e+27, 1.1362e+30],
        [7.1547e+22, 4.5828e+30, 1.2121e+04, 7.1846e+22]])

In [5]:
torch.zeros_like(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
torch.linspace(0,1,steps=100)

tensor([0.0000, 0.0101, 0.0202, 0.0303, 0.0404, 0.0505, 0.0606, 0.0707, 0.0808,
        0.0909, 0.1010, 0.1111, 0.1212, 0.1313, 0.1414, 0.1515, 0.1616, 0.1717,
        0.1818, 0.1919, 0.2020, 0.2121, 0.2222, 0.2323, 0.2424, 0.2525, 0.2626,
        0.2727, 0.2828, 0.2929, 0.3030, 0.3131, 0.3232, 0.3333, 0.3434, 0.3535,
        0.3636, 0.3737, 0.3838, 0.3939, 0.4040, 0.4141, 0.4242, 0.4343, 0.4444,
        0.4545, 0.4646, 0.4747, 0.4848, 0.4949, 0.5051, 0.5152, 0.5253, 0.5354,
        0.5455, 0.5556, 0.5657, 0.5758, 0.5859, 0.5960, 0.6061, 0.6162, 0.6263,
        0.6364, 0.6465, 0.6566, 0.6667, 0.6768, 0.6869, 0.6970, 0.7071, 0.7172,
        0.7273, 0.7374, 0.7475, 0.7576, 0.7677, 0.7778, 0.7879, 0.7980, 0.8081,
        0.8182, 0.8283, 0.8384, 0.8485, 0.8586, 0.8687, 0.8788, 0.8889, 0.8990,
        0.9091, 0.9192, 0.9293, 0.9394, 0.9495, 0.9596, 0.9697, 0.9798, 0.9899,
        1.0000])

In [7]:
x=torch.tensor([[1,2],[3,4],[4,7]])
x

tensor([[1, 2],
        [3, 4],
        [4, 7]])

In [8]:
x.size()

torch.Size([3, 2])

In [9]:
x[:,1]

tensor([2, 4, 7])

In [10]:
x[1,0:]

tensor([3, 4])

In [11]:
x[1,1].item()

4

In [12]:
type(x[1,1].item())

int

In [13]:
x.reshape(2, 3)

tensor([[1, 2, 3],
        [4, 4, 7]])

In [14]:
x.reshape(-1,1)

tensor([[1],
        [2],
        [3],
        [4],
        [4],
        [7]])

In [15]:
x.reshape(1,-1)

tensor([[1, 2, 3, 4, 4, 7]])

In [16]:
x=torch.ones(3,4)
y=torch.zeros(3,4)
z=torch.rand(3,4)

In [17]:
z.add(y)

tensor([[0.5818, 0.7254, 0.2727, 0.2086],
        [0.9172, 0.3616, 0.5749, 0.3563],
        [0.1340, 0.8123, 0.9088, 0.9883]])

In [18]:
z=y+z

In [19]:
# z numpy array to a torch tensor using torch.from_numpy, the generated tensor and the numpy array share the same memory

In [20]:
z*x

tensor([[0.5818, 0.7254, 0.2727, 0.2086],
        [0.9172, 0.3616, 0.5749, 0.3563],
        [0.1340, 0.8123, 0.9088, 0.9883]])

In [21]:
z.add_(y)

tensor([[0.5818, 0.7254, 0.2727, 0.2086],
        [0.9172, 0.3616, 0.5749, 0.3563],
        [0.1340, 0.8123, 0.9088, 0.9883]])

In [22]:
z

tensor([[0.5818, 0.7254, 0.2727, 0.2086],
        [0.9172, 0.3616, 0.5749, 0.3563],
        [0.1340, 0.8123, 0.9088, 0.9883]])

In [23]:
a=np.array([[1,2,3],[2,3,5]])
c=torch.from_numpy(a)
x=c.numpy()

In [24]:
x

array([[1, 2, 3],
       [2, 3, 5]])

In [25]:
#PYTORCH IS APPROX 5x Faster than numpy in terms of cpu computation. Numpy does not include GPU

#CUDA SUPPORT

In [26]:
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))


1
Tesla K80


In [27]:
cuda0=torch.device('cuda:0')

In [28]:
%%time
for i in range(10):
  m=torch.rand(10000,10000, device=cuda0)
  b=torch.ones(10000,10000, device=cuda0)
  l=torch.add(m,b)
print(l)

tensor([[1.3229, 1.0254, 1.0499,  ..., 1.6921, 1.1328, 1.6127],
        [1.6811, 1.5206, 1.6152,  ..., 1.8920, 1.7076, 1.2786],
        [1.6483, 1.6897, 1.6030,  ..., 1.2362, 1.0804, 1.6465],
        ...,
        [1.6232, 1.7747, 1.2570,  ..., 1.5897, 1.5621, 1.3951],
        [1.5066, 1.9976, 1.1832,  ..., 1.1491, 1.6818, 1.9116],
        [1.7293, 1.8903, 1.7939,  ..., 1.4886, 1.4027, 1.5584]],
       device='cuda:0')
CPU times: user 1.64 s, sys: 768 ms, total: 2.41 s
Wall time: 8.66 s


# AUTOGRAD

In [29]:
x=torch.ones([3,2], requires_grad=True)
y=x+3
z=y**3+x
t=torch.sum(z)
t

tensor(390., grad_fn=<SumBackward0>)

In [30]:
t.backward()

In [31]:
print(x.grad)

tensor([[49., 49.],
        [49., 49.],
        [49., 49.]])


In [32]:
x=torch.rand([3,2], requires_grad=True)
w=torch.rand([2,2], requires_grad=True)
b=torch.rand([1,2], requires_grad=True)
g=torch.matmul(x,w) +b
s=(1/(1+torch.exp(-g)))
s

tensor([[0.7326, 0.7918],
        [0.7242, 0.6937],
        [0.7334, 0.7039]], grad_fn=<MulBackward0>)

In [33]:
s.backward(torch.ones(3,2))

In [34]:
print(g.grad)

None


/usr/local/lib/python3.6/dist-packages/torch/tensor.py:746: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  warnings.warn("The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad "


In [35]:
x=torch.randn([20,1], requires_grad=True)
y=3*x-2

In [36]:
w=torch.tensor([1.], requires_grad=True)
b=torch.tensor([1.], requires_grad=True)

y_hat=w*x +b

loss=sum((y-y_hat)**2)
print(loss.item())

loss.backward()
print(b.grad.item(),w.grad.item())

201.171875
109.90025329589844 -36.32148361206055


In [41]:
w=torch.tensor([1.], requires_grad=True)
b=torch.tensor([1.], requires_grad=True)

lr=0.01

for i in range(45):
  x=torch.randn([20, 1])
  y=3*x-2
  y_hat=w*x+b
  loss=torch.sum((y_hat-y)**2)
  loss.backward()

  with torch.no_grad():
    w-=lr*w.grad
    b-=lr*b.grad

    w.grad.zero_()
    b.grad.zero_()
  
  print(w.item(), b.item())

  


1.6919664144515991 -0.05794966220855713
2.836798667907715 -0.9829415678977966
2.8510141372680664 -1.3862569332122803
3.0418477058410645 -1.659447193145752
2.986778974533081 -1.8009967803955078
3.00197434425354 -1.8814061880111694
3.0094895362854004 -1.9287070035934448
3.0078165531158447 -1.9565637111663818
3.002061128616333 -1.974303126335144
3.0015575885772705 -1.9845342636108398
3.000166177749634 -1.9907984733581543
3.000079870223999 -1.9944794178009033
2.9989376068115234 -1.9967037439346313
2.999567747116089 -1.998086929321289
2.999608039855957 -1.9988290071487427
2.999654531478882 -1.9992841482162476
2.9998278617858887 -1.9995704889297485
2.9999709129333496 -1.9997613430023193
3.00000262260437 -1.9998594522476196
3.0000014305114746 -1.9999157190322876
3.0000176429748535 -1.9999490976333618
3.000013589859009 -1.999968409538269
3.000007152557373 -1.9999817609786987
3.0000054836273193 -1.9999884366989136
3.000004529953003 -1.9999920129776
3.0000040531158447 -1.9999945163726807
3.00000

In [1]:
%%time
lr=0.001
n=10000000
epochs=2000

w=torch.rand([n], requires_grad=True, device=cuda0)
b=torch.ones([1], requires_grad=True, device=cuda0)

print(torch.mean(w).item(), b.item())

for i in range(epochs):
  x=torch.randn([n], device=cuda0)
  y=torch.dot(3*torch.ones([n], device=cuda0), x) -2

  y_hat= torch.dot(x, w) + b
  loss=torch.sum((y_hat - y)**2)

  loss.backward()

  with torch.no_grad():
    w-=lr*w.grad
    b-=lr*b.grad

    w.grad.zero_()
    b.grad.zero_()



NameError: ignored